#!/bin/sh -xeu

is_nightly_for_clippy() {
    # Fixed version of nightly for clippy.
    echo "${TRAVIS_RUST_VERSION}" | grep -qe "^nightly-.*"
}

is_stable() {
    [ "${TRAVIS_RUST_VERSION}" = "stable" ]
}

if [ "${1}" = "before_script" ]; then
    sudo apt-get -qq update
    sudo apt-get install -y \
            make \
            python3 \
            python-six \
            python3-six

    if is_nightly_for_clippy; then
        cargo "+${TRAVIS_RUST_VERSION}" install clippy --version "${CLIPPY_VERSION}" --force
    fi
    if is_stable; then
        rustup component add --toolchain stable rustfmt-preview
    fi
elif [ "${1}" = "script" ]; then
    if is_nightly_for_clippy; then
        cargo "+${TRAVIS_RUST_VERSION}" clippy --all --profile test
    fi
    if is_stable; then
        cargo fmt --all -- --write-mode=diff
    fi

    # Build / test existing code.
    cargo build --all
    cargo test --all

    cargo build --release --all
    cargo test --release --all

    if is_stable; then
        # Test generate.py.
        make test

        # Try to generate code from C sources.
        make generate
    fi
else
    printf "Unknown command: %s\n" "${1}" >&2
    exit 1
fi
